version: '3.2'
services:
  kali:
    image: skyjia/kali-docker-full:latest
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    volumes:
      - kali-root:/root
      - kali-postgres:/var/lib/postgresql
      - kali-data:/data
    network_mode: "host"
  kali-vnc:
    image: skyjia/kali-docker-full-vnc:latest
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    volumes:
      - kali-root:/root
      - kali-postgres:/var/lib/postgresql
      - kali-data:/data
    ports:
      - "5901:5901"
      - "6080:6080"
volumes:
  kali-root:
  kali-postgres:
  kali-data: